onlyBuiltDependencies:
  - core-js
  - esbuild
  - highlight.js
  - vuepress

allowBuilds:
  core-js: true
  esbuild: true
  highlight.js: true
  vuepress: true

neverBuiltDependencies: []
dangerouslyAllowAllBuilds: true