name: gen

on:
  push:
    branches:
      - main # 更新触发Actions的分支
  issues:
    types:
      [
        opened,
        closed,
        edited,
        milestoned,
        labeled,
        unlabeled,
        reopened,
        demilestoned,
      ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all # 必须，否则不能更新编译结果

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/checkout@v3
      - name: Download Issue and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm i
          pnpm action
          pnpm build
          pnpm run deploy
